CREATE DATABASE IF NOT EXISTS atp_dashboard;

CREATE TABLE IF NOT EXISTS atp_dashboard.collection_events
(
    event_key String,
    did String,
    collection String,
    rkey String,
    created_at Nullable(DateTime64(6, 'UTC')),
    created_at_key String,
    ingested_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(coalesce(created_at, toDateTime64('1970-01-01 00:00:00', 6, 'UTC')))
ORDER BY (event_key, collection, created_at_key);

-- MVP policy:
-- - Do not add TTL/delete rules for raw events without owner approval.
-- - Physical duplicate inserts are allowed; aggregation deduplicates with uniqExact(event_key).
-- - event_key is generated by the worker from Postgres values as:
--   length-prefixed(did, collection, rkey, created_at_key).

-- Storage observation query:
-- SELECT
--     database,
--     table,
--     formatReadableSize(sum(bytes_on_disk)) AS bytes_on_disk,
--     sum(rows) AS rows
-- FROM system.parts
-- WHERE active AND database = 'atp_dashboard' AND table = 'collection_events'
-- GROUP BY database, table;
